### ISSUE TITLE
Python does not recognise "serial.SerialTimeoutExeption"

### ISSUE THREAD

**Issue by LowSpecCorgi** [SagnikPradhan/the-knights#1]
Bug -> Python does not recognize `serial.SerialTimeoutExeption`
Error -> 
```
Traceback (most recent call last):
  File "C:\Users\rohan\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\rohan\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\rohan\Documents\GitHub\the-knights\backend\src\app.py", line 49, in run_serial
    serial_loop()
  File "c:\Users\rohan\Documents\GitHub\the-knights\backend\src\app.py", line 21, in serial_loop
    except serial.SerialTimeoutExeption:
**AttributeError: module 'serial' has no attribute 'SerialTimeoutExeption'**
```

**Comment by LowSpecCorgi** [comment]
> The bug is located here:

```python
# Serial loop for reading serial port data
def serial_loop():
    print("Entering serial loop...")
    while True:
        # why is there a question mark??
        #? Serial port reading
        try:
            #TODO implement actual data handling
            data = json.dumps(ser.readline())
        except serial.SerialTimeoutExeption:
            print("Data could not be read (serial timeout)")
```

**Comment by LowSpecCorgi** [comment]
Fixed issue with lasted commit.
